#
#  WD-PurePerms - A WaterDogPE plugin that attempts at being fully compatible with PurePerms
#  Copyright (C) 2021  Funniray
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  I am available for any questions/requests: funniray10@gmail.com
#

###############################################################################################################
###############################################################################################################
####                                                                                                       ####
####                               IF YOU PAID FOR THIS, YOU WERE SCAMMED                                  ####
####                                     THIS IS A FREE PLUGIN                                             ####
####                           https://github.com/funniray/waterdog-pureperms                              ####
####                           Report scammers to beingscammed@reallyisnt.fun                              ####
####                                                                                                       ####
###############################################################################################################
###############################################################################################################

showpiracywarning: true

jdbcurl: "jdbc:mysql://localhost:3306/pureperms"
dbusername: "root"
dbpassword: ""